### ISSUE TITLE
Firefox can't open this page

### ISSUE THREAD

**Issue by UncleEnk** [excalith/excalith-start-page#3]
I have been having this issue whenever I search anything where Firefox says: 
> Firefox Can’t Open This Page
>
> To protect your security, www.google.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

I am not sure how to fix this as it is an issue with Firefox and I have not found anything in https://about:config that will help

**Comment by excalith** [comment]
It is blocked by default on browsers for many security concerns. However, I am not using any x-frames to render any page, which is odd.

- Are you able to launch google.com without www?
- You might have some firefox settings or extensions to explicitly disable launching pages with _self with some functionality required for such applications.
- For a workaround as firefox mentioned, using targets as _blank instead of _self should keep it working if you do not want to hassle with security settings and such.

Please let me know what happens

For future reference, this issue is related to a security topic of Firefox located in https://support.mozilla.org/en-US/kb/xframe-neterror-page

**Comment by UncleEnk** [comment]
ty i will look into what you are saying

**Comment by UncleEnk** [comment]
YES, i fixed it by changing the target to _blank from _self as you described. tysm
