### ISSUE TITLE
[BUG] target doesn’t apply

### ISSUE THREAD

**Issue by rohansharma-developer** [excalith/excalith-start-page#71]
The ”target” field in ”URLLaunch” in the config doesn’t actually work. I tried changing its value to “_blank” which means that it would open every link in a new tab but it actually doesn’t….

**Comment by mureev** [comment]
+1, I've noticed the same. as a result links for me open differently. I have a mix of IP and domain name links and they act differently.

I've tried changing urlLaunch / target, but its not making any affect. it appears, that its not applied.

Example of URLs:
1. http://192.168.1.1/
2. https://notion.com/

**Comment by excalith** [comment]
Sorry for the delay guys, having some health related stuff lately. After a huge refactoring, I believe I forgot to update the filtered links. The urls that clicked was intended to launch within the same window, but I realise this is confusing so changed it as well.

Here is the upcoming hotfix:
- Clicking links will read target from settings instead of opening within same page
- Fixed an issue filtered links does not read target from settings if only 1 filtered option is available

Will do some tests and release it as soon as possible.

**Comment by mureev** [comment]
thanks a ton and take core! hope you get better soon!
